services:
  - type: web
    name: alles-unter-einem-dach
    runtime: static
    buildCommand: "echo 'No build needed'"
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
